Console.WriteLine("Anonymous Income Comparison Program");
Console.WriteLine("Person 1");
Console.WriteLine("Hourly Rate?");
double hourlyRate1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Hours worked per week?");
double hoursWorked1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Person 2");
Console.WriteLine("Hourly Rate?");
double hourlyRate2 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Hours worked per week?");
double hoursWorked2 = Convert.ToDouble(Console.ReadLine());
double annualSalary1 = hourlyRate1 * hoursWorked1 * 52;
double annualSalary2 = hourlyRate2 * hoursWorked2 * 52;
Console.WriteLine("Annual salary of Person 1:");
Console.WriteLine(annualSalary1);
Console.WriteLine("Annual salary of Person 2:");
Console.WriteLine(annualSalary2);
Console.WriteLine("Does Person 1 make more money than Person 2?");
bool doesPerson1MakeMore = annualSalary1 > annualSalary2;
Console.WriteLine(doesPerson1MakeMore);